run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - bodyclose
    - gosec
    - misspell

linters-settings:
  gosec:
    # G104 (erros não tratados) já é coberto pelo errcheck
    excludes:
      - G104
  errcheck:
    check-type-assertions: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0
